"""add evidence_skill unique constraint

Revision ID: dadf094face4
Revises: 8c5e3d88bc63
Create Date: 2026-09-19 15:06:23.096359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadf094face4'
down_revision: Union[str, Sequence[str], None] = '8c5e3d88bc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_evidence_skill', 'evidence_skill', ['evidence_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_evidence_skill', 'evidence_skill', type_='unique')
    # ### end Alembic commands ###
